
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hhh
      username: root
      password: 123
    mvc:
          view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    thymeleaf:
      cache: false
      enabled: false
    jpa:
      hibernate:
        ddl-auto: update


